import {NextIntlClientProvider} from 'next-intl';
import {getLocale} from 'next-intl/server';
import { Toaster } from "react-hot-toast";
import Providers from "./providers";
import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport = {
    viewport: "user-scalable=0, initial-scale=1, maximum-scale=1, width=device-width",
}

export default async function RootLayout({ children }) {

    const locale = await getLocale();

    return (
        <html lang={locale}>
        <body className={inter.className}>
        <NextIntlClientProvider>
        <Providers>
            <Toaster position="top-right" />
            {children}
        </Providers>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
